//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Atencion
    {
        public TB_Atencion()
        {
            this.TB_DatosMedicos = new HashSet<TB_DatosMedicos>();
        }
    
        public int codigo { get; set; }
        public int cp { get; set; }
        public int fp { get; set; }
        public int ndau { get; set; }
        public short atensol { get; set; }
        public int servsol { get; set; }
        public int actisol { get; set; }
        public int profsol { get; set; }
        public System.DateTime fechalleg { get; set; }
        public Nullable<System.DateTime> fechaper { get; set; }
        public int motivo { get; set; }
        public Nullable<int> medio { get; set; }
        public Nullable<int> lugar { get; set; }
        public short ateneje { get; set; }
        public int serveje { get; set; }
        public int actieje { get; set; }
        public int profeje { get; set; }
        public string comentario { get; set; }
        public short anulado { get; set; }
        public Nullable<int> motanul { get; set; }
        public Nullable<System.DateTime> cierre { get; set; }
        public int uscrea { get; set; }
        public System.DateTime fcrea { get; set; }
        public int usmod { get; set; }
        public System.DateTime fmod { get; set; }
        public Nullable<int> consultorio { get; set; }
    
        public virtual TB_Box TB_Box { get; set; }
        public virtual TB_Especialidad TB_Especialidad { get; set; }
        public virtual TB_Especialidad TB_Especialidad1 { get; set; }
        public virtual TB_Lugar TB_Lugar { get; set; }
        public virtual TB_MedioLlegada TB_MedioLlegada { get; set; }
        public virtual TB_Motivo TB_Motivo { get; set; }
        public virtual TB_MotivoAnula TB_MotivoAnula { get; set; }
        public virtual TB_Paciente TB_Paciente { get; set; }
        public virtual TB_Profesional TB_Profesional { get; set; }
        public virtual TB_Profesional TB_Profesional1 { get; set; }
        public virtual TB_Servicio TB_Servicio { get; set; }
        public virtual TB_Servicio TB_Servicio1 { get; set; }
        public virtual TB_Signos TB_Signos { get; set; }
        public virtual TB_Usuario TB_Usuario { get; set; }
        public virtual TB_Usuario TB_Usuario1 { get; set; }
        public virtual ICollection<TB_DatosMedicos> TB_DatosMedicos { get; set; }
    }
}
