//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Box
    {
        public TB_Box()
        {
            this.TB_Atencion = new HashSet<TB_Atencion>();
            this.TB_DatosMedicos = new HashSet<TB_DatosMedicos>();
        }
    
        public int codigo { get; set; }
        public string box { get; set; }
        public string camilla { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> dau { get; set; }
    
        public virtual ICollection<TB_Atencion> TB_Atencion { get; set; }
        public virtual ICollection<TB_DatosMedicos> TB_DatosMedicos { get; set; }
    }
}
