//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Comuna
    {
        public TB_Comuna()
        {
            this.TB_Paciente = new HashSet<TB_Paciente>();
        }
    
        public int codigo { get; set; }
        public int codexterno { get; set; }
        public string codusuario { get; set; }
        public string denominacion { get; set; }
        public string descripcion { get; set; }
        public short tipo { get; set; }
        public Nullable<int> padre { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<TB_Paciente> TB_Paciente { get; set; }
    }
}
