//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Condicion
    {
        public TB_Condicion()
        {
            this.TB_DatosMedicos = new HashSet<TB_DatosMedicos>();
            this.TB_DatosMedicos1 = new HashSet<TB_DatosMedicos>();
        }
    
        public int codigo { get; set; }
        public string codusuario { get; set; }
        public string denominacion { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual ICollection<TB_DatosMedicos> TB_DatosMedicos { get; set; }
        public virtual ICollection<TB_DatosMedicos> TB_DatosMedicos1 { get; set; }
    }
}
