//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_DatosMedicos
    {
        public int codigo { get; set; }
        public int nrodau { get; set; }
        public Nullable<int> cp { get; set; }
        public System.DateTime atencion { get; set; }
        public int coning1 { get; set; }
        public Nullable<int> coning2 { get; set; }
        public short pronostico { get; set; }
        public short alcoholemia { get; set; }
        public Nullable<System.DateTime> fechaalc { get; set; }
        public Nullable<short> datoalc { get; set; }
        public short destino { get; set; }
        public Nullable<int> servdest { get; set; }
        public short ambulancia { get; set; }
        public Nullable<short> carabinero { get; set; }
        public string placacarab { get; set; }
        public Nullable<int> policlinico { get; set; }
        public Nullable<int> diagpos1 { get; set; }
        public Nullable<int> diagpos2 { get; set; }
        public Nullable<int> perstratante { get; set; }
        public int uscrea { get; set; }
        public System.DateTime fcrea { get; set; }
        public int usmod { get; set; }
        public System.DateTime fmod { get; set; }
        public Nullable<System.DateTime> fsigno { get; set; }
        public Nullable<short> color { get; set; }
        public Nullable<short> riesgo { get; set; }
        public string indicaciones { get; set; }
        public Nullable<int> box { get; set; }
    
        public virtual TB_Atencion TB_Atencion { get; set; }
        public virtual TB_Box TB_Box { get; set; }
        public virtual TB_Condicion TB_Condicion { get; set; }
        public virtual TB_Condicion TB_Condicion1 { get; set; }
        public virtual TB_Diagnostico TB_Diagnostico { get; set; }
        public virtual TB_Diagnostico TB_Diagnostico1 { get; set; }
        public virtual TB_Paciente TB_Paciente { get; set; }
        public virtual TB_Profesional TB_Profesional { get; set; }
        public virtual TB_Servicio TB_Servicio { get; set; }
        public virtual TB_Servicio TB_Servicio1 { get; set; }
        public virtual TB_Usuario TB_Usuario { get; set; }
        public virtual TB_Usuario TB_Usuario1 { get; set; }
    }
}
