//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Lugar
    {
        public TB_Lugar()
        {
            this.TB_Atencion = new HashSet<TB_Atencion>();
        }
    
        public int codigo { get; set; }
        public string codusuario { get; set; }
        public string denominacion { get; set; }
        public string descripcion { get; set; }
        public int estado { get; set; }
    
        public virtual ICollection<TB_Atencion> TB_Atencion { get; set; }
    }
}
