//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Paciente
    {
        public TB_Paciente()
        {
            this.TB_Atencion = new HashSet<TB_Atencion>();
            this.TB_DatosMedicos = new HashSet<TB_DatosMedicos>();
        }
    
        public int codpacie { get; set; }
        public System.DateTime fechacrea { get; set; }
        public short estado { get; set; }
        public Nullable<int> rut { get; set; }
        public string digiver { get; set; }
        public string hc { get; set; }
        public string apellpat { get; set; }
        public string apellmat { get; set; }
        public string nombres { get; set; }
        public Nullable<System.DateTime> fechanac { get; set; }
        public Nullable<System.DateTime> fechafall { get; set; }
        public short sexo { get; set; }
        public short estcivil { get; set; }
        public int formapago { get; set; }
        public string credencial { get; set; }
        public Nullable<System.DateTime> vigencia { get; set; }
        public string domicilio { get; set; }
        public Nullable<int> comuna { get; set; }
        public string telefono { get; set; }
        public Nullable<short> etnia { get; set; }
        public string contacto { get; set; }
        public string nombrepad { get; set; }
        public string nombremad { get; set; }
        public string observacion { get; set; }
        public int usmod { get; set; }
        public System.DateTime fmod { get; set; }
        public int uspago { get; set; }
        public System.DateTime fpago { get; set; }
        public string nacionalidad { get; set; }
    
        public virtual ICollection<TB_Atencion> TB_Atencion { get; set; }
        public virtual TB_Comuna TB_Comuna { get; set; }
        public virtual ICollection<TB_DatosMedicos> TB_DatosMedicos { get; set; }
        public virtual TB_Fpago TB_Fpago { get; set; }
        public virtual TB_Usuario TB_Usuario { get; set; }
        public virtual TB_Usuario TB_Usuario1 { get; set; }
    }
}
