//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Signos
    {
        public TB_Signos()
        {
            this.TB_Atencion = new HashSet<TB_Atencion>();
        }
    
        public int Codigo { get; set; }
        public int nrodau { get; set; }
        public System.DateTime fechasigno { get; set; }
        public string presion { get; set; }
        public string tempaxilar { get; set; }
        public string temprectal { get; set; }
        public string pulso { get; set; }
    
        public virtual ICollection<TB_Atencion> TB_Atencion { get; set; }
    }
}
