//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Servicio
    {
        public TB_Servicio()
        {
            this.TB_Atencion = new HashSet<TB_Atencion>();
            this.TB_Atencion1 = new HashSet<TB_Atencion>();
            this.TB_DatosMedicos = new HashSet<TB_DatosMedicos>();
            this.TB_DatosMedicos1 = new HashSet<TB_DatosMedicos>();
        }
    
        public int codservicio { get; set; }
        public string codusuario { get; set; }
        public Nullable<int> padre { get; set; }
        public string denominacion { get; set; }
        public string descripcion { get; set; }
        public short servinst { get; set; }
        public Nullable<int> instexte { get; set; }
        public int lugar { get; set; }
        public short activo { get; set; }
    
        public virtual ICollection<TB_Atencion> TB_Atencion { get; set; }
        public virtual ICollection<TB_Atencion> TB_Atencion1 { get; set; }
        public virtual ICollection<TB_DatosMedicos> TB_DatosMedicos { get; set; }
        public virtual ICollection<TB_DatosMedicos> TB_DatosMedicos1 { get; set; }
    }
}
