//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Usuario
    {
        public TB_Usuario()
        {
            this.TB_Atencion = new HashSet<TB_Atencion>();
            this.TB_Atencion1 = new HashSet<TB_Atencion>();
            this.TB_DatosMedicos = new HashSet<TB_DatosMedicos>();
            this.TB_DatosMedicos1 = new HashSet<TB_DatosMedicos>();
            this.TB_Paciente = new HashSet<TB_Paciente>();
            this.TB_Paciente1 = new HashSet<TB_Paciente>();
        }
    
        public int id { get; set; }
        public string usr { get; set; }
        public string nombre { get; set; }
        public string pass { get; set; }
        public int tipo { get; set; }
        public int estado { get; set; }
    
        public virtual ICollection<TB_Atencion> TB_Atencion { get; set; }
        public virtual ICollection<TB_Atencion> TB_Atencion1 { get; set; }
        public virtual ICollection<TB_DatosMedicos> TB_DatosMedicos { get; set; }
        public virtual ICollection<TB_DatosMedicos> TB_DatosMedicos1 { get; set; }
        public virtual ICollection<TB_Paciente> TB_Paciente { get; set; }
        public virtual ICollection<TB_Paciente> TB_Paciente1 { get; set; }
    }
}
